#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           m1,            tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           m2,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           m3,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

nMotorEncoder[m1] = 0;
nMotorEncoder[m2] = 0;
nMotorEncoder[m3] = 0;
motor[m1] = 127;
waitUntil(nMotorEncoder[m1] >= 720);
motor[m1] = 0;
nMotorEncoder[m1] = 0;
nMotorEncoder[m2] = 0;
nMotorEncoder[m3] = 0;
motor[m2] = 127;
waitUntil(nMotorEncoder[m2] >= 720);
motor[m2] = 0;
nMotorEncoder[m1] = 0;
nMotorEncoder[m2] = 0;
nMotorEncoder[m3] = 0;
motor[m3] = 127;
waitUntil(nMotorEncoder[m3] >= 720);
motor[m3] = 0;

}
