#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    mobile1,        sensorPotentiometer)
#pragma config(Sensor, in2,    mobile2,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           mobileRight,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FRLift,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           BRLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           slider,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BLLift,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           rightDrive,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           FLLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mobileLeft,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void go_forth(int time, int speed=127)
{
	motor[leftDrive]=speed;
	motor[rightDrive]=speed;
	wait1Msec(time);
	motor[leftDrive]=0;
	motor[rightDrive]=0;
}
void go_back(int time, int speed=-127)
{
	motor[leftDrive]=speed;
	motor[rightDrive]=speed;
	wait1Msec(time);
	motor[leftDrive]=0;
	motor[rightDrive]=0;
}
void turn(int time, int speed=127)
{
	motor[leftDrive]=speed;
	motor[rightDrive]=-speed;
	wait1Msec(time);
	motor[leftDrive]=0;
	motor[rightDrive]=0;
}
void liftMobileGoal(int time, int speed=127)
{
	motor[mobileLeft] = speed;
	motor[mobileRight] = speed;
	wait1Msec(time);
	motor[mobileLeft]=0;
	motor[mobileRight]=0;
}

void scissorLift(int time, int speed=127)
{
	motor[FLLift] = -speed;
	motor[FRLift] = speed;
	motor[BLLift] = speed;
	motor[BRLift] = -speed;
	wait1Msec(time);
	motor[FLLift]= 0;
	motor[FRLift]= 0;
	motor[BLLift]= 0;
	motor[BRLift]= 0;
}

void openClaw(int speed=127)//negitive to close
{
	motor[claw] = speed;
}
void stopClaw(int time)
{
	wait1Msec(time);
	motor[claw] = 0;
}
void moveSlider(int time, int speed=127)
{
	motor[slider] = speed;
	wait1Msec(time);
	motor[slider] = 0;
}
